### ISSUE TITLE
Add support for incubator.wikimedia.org

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1180]
Some projects involve new users editing on the incubator wiki. We'll need to special-case this in `Wiki` as we do with wikidata.

**Comment by bachounda** [comment]
hi 
Is it possible to integrate incubator projects into the dashboard because students in our education program.https://outreachdashboard.wmflabs.org/courses/Chlef_university__Algeria/Wikipedia_education_program__2016-2017

They also contribute to the incubator

Otherwise I really use the dashboard / and I think it's a great program

We discovered another way to use the dashboard in contest - we "jury members" can follow contributors contests with the dashboard and it's very easy
