### ISSUE TITLE
improve Uploads tab layout

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1284]
The Uploads tab currently acts as simply a recent uploads feed, and doesn't help much with either getting an overview of all contributed Uploads (where a justified gallery would fit many more images for a good overview) or evaluating uploads on a user-by-user basis. (Currently, you can sort by username, but can't easily get to the Commons upload page for a user, and also there's no visible grouping by user even when you've sorted by username.)

**Comment by aSquare14** [comment]
I'd like to work on this !

**Comment by ragesoss** [comment]
Great! Starting with wireframes might be helpful.

**Comment by yunjuc** [comment]
I'll tackle on this as well.

**Comment by yunjuc** [comment]
Here is what I have in mind - a grid view photo gallery with the following information:
- Description (instead of filename, which is less informative)
- Thumbnail (link to source page)
- Uploaded by
- Usage count (omit when usage is 0)

![upload](https://user-images.githubusercontent.com/18255878/36301146-ae5bd976-12b8-11e8-84bc-be2a811103f7.png)

When users click on author name, they will be taken to another page with the same layout, only the page title is slightly different. Users can go back to the previous page using the back button or the upload button.

![author](https://user-images.githubusercontent.com/18255878/36301167-b8525180-12b8-11e8-8f35-c943c5627e3b.png)

Thought?

**Comment by ragesoss** [comment]
This is going in the right direction. I'm not sure about the separate view for a single user; that should definitely not be done in the initial implementation, but maybe something like that would make sense later. I think we'd want to do it as a filter on the same set of images, rather than a separate page.

For the layout, I think it's important to use as much space as possible; padding should be limited or removed. Justified gallery layouts are ideal for this kind of thing, in my opinion.

**Comment by yunjuc** [comment]
Agree on the filter usage.

Also agree justified gallery looks better. So maybe mouseover to surface text and click linking to source page?

**Comment by ragesoss** [comment]
Yeah, something like that might work nicely.

**Comment by yunjuc** [comment]
Ok, I'll start working on this.

**Comment by ragesoss** [comment]
We've made a lot of progress on this, and I think the design is in pretty good shape now.
