### ISSUE TITLE
Add Jest tests for untested React components

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1510]
The core of the Dashboard user interface — course pages — uses React.js. We have a test system set up for unit tests of Javascript and JSX files, consisting of:
* [Jest](https://facebook.github.io/jest/) - the framework that runs the JS test suite
* [Enzyme](http://airbnb.io/enzyme/) - a tool for interacting with isolated React components for testing
* [Chai](http://chaijs.com/) - an assertion library used for writing the tests

The Javascript tests live in the `test` directory. (The `spec` directory holds the Ruby-based Rspec tests.)

Some components have tests, but most do not, and many that do have only very partial test coverage. You can run the whole test suite with `yarn test` to get a coverage report (which appears in `/coverage/lcov-report/index.html`) and see the coverage details.

Choose a component that lacks tests, and write a comprehensive set of tests for it, exercising as much of the component's functionality as possible.

Please use existing Enzyme-based tests as examples to follow, rather than the older tests that use ReactTestUtils. ReactTestUtils is deprecated for this project; all new tests should use Enzyme, as it is much easier to work with for React components.

Submit one PR per component. Leave a comment here to note which component you are working on.

**Comment by hoslack** [comment]
I want to work on this issue @ragesoss , Please invite me if possible.

**Comment by HartiganHM** [comment]
Hi there! I’m a first-time contributor and was hoping to help out with this issue. I noticed nobody was assigned to it, but interest has been shown. There are several components to still test, so I think it would be doable to take the `uploads` component tests. I’m happy to try helping out elsewhere as well.  Thanks!

**Comment by maryam21** [comment]
Hi! I'd like help in this issue as well. I want to work on tests for 'user_profiles' component if nobody is working on it.

**Comment by ragesoss** [comment]
@airum82 go for it. I'm not very satisfied with our current patterns for component testing, so feel free to approach such tests in whatever way you think makes sense. I know there are some best practices that have been emerging recently around component tests that I haven't followed the details of.

Another area of testing that would likely be more straightforward and less likely to change over time would be tests for the reducers. We have a few fairly complex reducers, but testing such things can be pretty simple since they are supposed to be pure functions.

**Comment by benpolinsky** [comment]
@ragesoss Hi.

Just got a build up and running locally. I see there's tons of test coverage to make up. I'd love to help out. 

Personal opinion is that [react-testing-library](https://github.com/kentcdodds/react-testing-library) has a better philosophy to testing and simpler API than enzyme, but I can understand if you don't want to introduce a third way of testing React Components.

Let me know :)

**Comment by ragesoss** [comment]
@benpolinsky I'd love to see a best-practices example of what it would look like to test a nontrivial component using `react-testing-library`. I'd like to find a clear and consistent pattern for doing component tests.

@bwreid do you have opinions about react-testing-library vs. enzyme?

**Comment by bwreid** [comment]
I'm down for whatever works best.  :)  We'll need to accommodate the following with any set of tools:
* Mocking API calls
* Routing
* Redux
* User Interaction

It looks like `react-testing-library` has examples for all of those, so I'd be up for making the switch. There are probably lots of places to start but let us know if you're looking for some guidance @benpolinsky

**Comment by benpolinsky** [comment]
@ragesoss @bwreid I think the biggest shift from `enzyme` to `react-testing-library` is ditching [shallow rendering](https://github.com/airbnb/enzyme/blob/master/docs/api/shallow.md), replacing it with plain mocks. 

Briefly, the idea is that shallow rending is too heavy-handed, always mocking all children of a component. The philosophy is [laid out fairly well here.](https://blog.kentcdodds.com/why-i-never-use-shallow-rendering-c08851a68bb7) Perhaps it leads to slightly 'more intergration-y' tests as opposed to strict unit tests, but I've found that to be a generally positive shift in mindset. 

I always thought there was a weird layer of abstraction when testing components with `enzyme`, so `react-testing-library` was a welcome change. With the latter, you can always choose to mock all children if you'd like. 

At any rate, I've written a test for `special_users_list.jsx`. I've noticed there are some other *_list tests, but no test for `list.jsx`, so that might be a good place to start: It's definitely not trivial. I'll issue a PR later on in the week and we can discuss.

**Comment by ragesoss** [comment]
@GLADYS-CODES you're welcome to work on this. It's best done in small pieces, ideally one PR per component.

**Comment by GLADYS-CODES** [comment]
ok

**Comment by ragesoss** [comment]
We've now deleted all the Jest tests, so I'm closing this issue.
