### ISSUE TITLE
Add i18n support for training module index pages and library pages

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1552]
For P&E Dashboard, we need to be able to translate the module descriptions and titles.

**Comment by tulikavijay** [comment]
hi! can i take this up?

**Comment by ragesoss** [comment]
@tulikavijay sure. I think @bcb37 is in the middle of some related i18n work, but isn't working on this particular part of it. Send me an email — sage at wikiedu.org — and I can send you an invite to the project Slack.

**Comment by tulikavijay** [comment]
Can you point me to the files/folder , where i have to make changes? i tried to figure it out myself but i couldn't.

**Comment by ragesoss** [comment]
@tulikavijay there are a few parts to this:

1. Getting translations from meta.

I created some training wiki pages for convenient development on this. You can set these values in application.yml:

```
  training_slides_wiki_page: 'Training modules/dashboard/slides-i18n-test'
  training_modules_wiki_page: 'Training modules/dashboard/modules-i18n-test'
  training_libraries_wiki_page: 'Training modules/dashboard/libraries-i18n-test'
```

Then you can reload content from the wiki by visiting `/reload_trainings?module=all`.

Here are the corresponding wiki pages:
* https://meta.wikimedia.org/wiki/Training_modules/dashboard/slides-i18n-test
* https://meta.wikimedia.org/wiki/Training_modules/dashboard/libraries-i18n-test
* https://meta.wikimedia.org/wiki/Training_modules/dashboard/modules-i18n-test

The relevant part is the module — https://meta.wikimedia.org/wiki/User:JSutherland_(WMF)/dashboard_modules/keeping_events_safe.json — which uses this translated wiki page:
* https://meta.wikimedia.org/wiki/Training_modules/Keeping_events_safe/description

When you reload the training data, the dashboard uses `lib/trainings/training_loader` to pull in the content. It might be pulling in the translations already, or you might need to make some adjustments to the reload_trainings system to ensure that it does get the translations.

2. Serve the relevant translation based on user locale.

The relevant templates are in `views/training`.

Fixing the breadcrumbs may be the most challenging part. The breadcrumbs get configured in TrainingController via callsed to `add_breadcrumb` (which is provided by the breadcrumbs_on_rails gem), but it will take some work to add i18n support for that.

**Comment by bcb37** [comment]
@tulikavijay  , are you still working on this?

**Comment by ragesoss** [comment]
@bcb37 I don't think so. If you're up for this one, please go for it.

**Comment by bcb37** [comment]
This issue seems to have a bureaucratic block. As I currently understand it, the middle breadcrumb link, and some other short text content associated with libraries, exist only in json files, and so are not translatable mediawiki resources. For testing purposes, I've created a wiki page (https://meta.wikimedia.org/wiki/Training_libraries/Support_and_Safety/description) from the text in this json file (https://meta.wikimedia.org/wiki/User:Benblanchard/dashboard_libraries/support_and_safety_library.json) with content that preserves the json hierarchy.  This page is in theory translatable, but it would require an administrator to make it so. 

It may also be worthwhile to think about getting the module descriptions from the modules themselves, and also maybe generating the wiki page automatically from the json. They would both be doing double duty: presenting a friendly translatable text format (which wiki pages are good at), and maintaining the library's hierarchy in a data structure (which json is good at). 

We could just decide to parse a bit of json and then figure out how to find the associated translations, but I think there should be input from those creating the libraries and their translations as to where they want them to be maintained.

**Comment by ragesoss** [comment]
Sorry about the delay is getting the translation side of things available. I'm trying a different tack now to find someone to enable it.

**Comment by ragesoss** [comment]
This is done, thanks to Amit.
