### ISSUE TITLE
Instructors should be able to (optionally) customize the names of weeks in the timeline

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1611]
We have a `title` attribute for `Week` records, but we no longer use it because in most cases it is unnecessary additional complexity.

## feature request
"Their institutions don't count spring breaks or ski breaks in their "weekly" course schedules. 

So once students reach "week 4, no classes this week" on the Dashboard (which might be spring break) and return to the Dashboard for "week 5" their actual course calendars call that week after spring break "week 4" - This just leads to problems with matching up the calendar on the Dashboard with their syllabus and their university schedules. And does create a lot of problems around verbal confirmation of assignments for students. 

If we can include this on a request list for technical changes, a lot of people would like the "week __" piece of the timeline to be customizeable, so you can update not only the "weeks" but you would in theory make it "part 1" or "assignment 1" instead. "

**Comment by davidnoahball** [comment]
I'd like to take a stab at this. Am I good to go, @ragesoss? Any input or heads-ups for a first-time contributor?

**Comment by ragesoss** [comment]
@davidnoahball you're welcome to take this on, but it's a relatively complex issue in terms of how much context about how the app works that will be relevant. It's likely to require frontend changes, backend changes, and new Capybara feature specs. Depending on your goals, it might be better to start with a more isolated issue.

If you'd like an invite to our slack channel, let me know.

**Comment by davidnoahball** [comment]
Slack chat transcript:

David Ball [1:46 PM]
Hey, @ragesoss. I'm starting to dig into 1611 (https://github.com/WikiEducationFoundation/WikiEduDashboard/issues/1611) and I've come to an issue I want to clear up.

In the ticket it mentions the "`title` attribute for `Week` records", but it looks like in the `weeks` table, there are only entries for weeks that have active days. Given the description of the task, it seems I'd also have to include non-work-week days in the table if I were to go that route (to make all weeks' titles editable). This would be a major refactor given that much of the weeks functionality is built on the current strategy of storing only work-weeks in the table and determining non-work-weeks on the fly using `week_meetings` data (e.g. `timeline.jsx :201`). As an example, the way that weeks are not tied to dates directly, and will therefore restructure themselves to fill available dates if the active Project Dates are changed, depends on this.

Additionally, because of this 'restructuring' functionality, if titles were attached to weeks, then when the weeks changed relative position, the titles would move with them. For example, if an additional non-work-week was added to the middle of a project, all the weeks titles after that would be "pushed" up one. This does not seem to be intended functionality based on the issue description, although I suppose it's left to interpretation.

All this to say, I think that instead of using the `title` attribute on weeks, it would be better to add a new `weeks_titles` table linking custom titles to dates (instead of weeks by id), and then using that data if available in `week.jsx :196`, `timeline.jsx :348`, and `empty_week.jsx :65`, which covers the Timeline main body and side-nav. The titles would be individually editable on the main body via a pencil icon to the right of the title if the user has edit permissions. Please let me know if this all seems sound to you. (edited) 


ragesoss [1:48 PM]
hmm...
I think the easiest solution would be to only allow editing of weeks that correspond to Week records, and not empty weeks.
I think decouple titles from the weeks, and instead connecting them to dates, is likely to be a really confusing thing in some cases, when the dates get changed to add a new empty week but the titles correspond the the content of the weeks rather than the date of them.

David Ball [1:52 PM]
I suppose that would be easiest, but in certain cases it would lead to weird results. For example, in the ticket description it mentions that a teacher might want to adjust a holiday week to not "count", to match the student's calendars. Trying to do this without being able to edit the holiday week to, say "Winter Break", would lead to double-titles: "Week 7, Week 8, Week 8, Week 9" instead of "Week 7, Winter Break, Week 8, Week 9". (edited) 
I'll leave the decision to you, though.

ragesoss [1:57 PM]
I see two possible solutions to that... either change the empty week titles so that they are not numbered ever, or change them so that they are not numbered *if* there are any user-named weeks in the timeline.

David Ball [2:00 PM]
They seem about equivalent in implementation complexity and functional justification to me, so I'll let you decide based on your experience (edited) 

ragesoss [2:00 PM]
you mean, those two possible solutions? Or that route vs. the weeks_titles table?

David Ball [2:01 PM]
I mean on when to number empty weeks. (edited) 

ragesoss [2:01 PM]
Hmm...
I think the second one would be preferable.
That keeps the behavior the same by default...
and then the empty week title when there are any titled weeks could be `week of <date> - <date>`

David Ball [2:03 PM]
Alright, sounds good. I'll cross-post this conversation in the ticket for clarity if that's alright with you.

**Comment by davidnoahball** [comment]
Pull request made

**Comment by ragesoss** [comment]
Fixed with https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/2652
