### ISSUE TITLE
Recent Edits sorting is wonky

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1638]
Sorting is somehow implemented for the Recent Edits table (`/recent-activity/recent-edits`), probably via the List component. However, it doesn't work that well. Sorting by date does not work, and all the other sorting only works ascending; clicking again does not reverse the sorting like it does in some other tables.

Figuring how how to implement sorting nicely for redux-backed tables, starting with this one, would be a welcome improvement.

**Comment by ragesoss** [comment]
I think I cracked the sorting nut, more or less, in the new `users` reducer and the model_utils `sortByKey` helper function.

**Comment by khyatisoneji** [comment]
Hey @ragesoss , I was able to find out the problem and fix it. However there is a css issue still as I mentioned in this gif.

![recent-edits page](https://user-images.githubusercontent.com/31898080/35470109-75411a9c-0369-11e8-9dd7-110d253bef9c.gif)

The issue is in sortItems function in activity_table.jsx file.

Here we are removing 'asc' or 'desc' class from all the table headers and hence losing information about the state of sorting.

Shall I send a PR about this issue?

**Comment by ragesoss** [comment]
Sure, let's see what you've got.

**Comment by psinghal20** [comment]
@ragesoss As the existing PR is not solving the issue, can I look into this issue if nobody is working on this?

**Comment by ragesoss** [comment]
@psinghal20 go for it. khyatisoneji isn't working on it further.
