### ISSUE TITLE
Download stats modal appears underneath Milestones component

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#1848]
![stacking problem](https://user-images.githubusercontent.com/848483/38383129-82cae940-38c0-11e8-9c99-5b5fb1126868.png)

This appears to be related to Milestones having `position: relative` from the `module` class, but there are other components on the page that also have the `module` class but don't have this behavior. I don't understand the CSS well enough to diagnose the problem, but if we can sort out the root cause rather than just work around the bug for this particular component, that would be ideal.

**Comment by yunjuc** [comment]
Where is the download? I've been poking around but still can't find it...

**Comment by ragesoss** [comment]
@yunjuc it will show up in Available Actions on the home tab if the course is 'published' (ie, has at least one campaign) you are an admin or instructor for it.

**Comment by yunjuc** [comment]
There is the fix, the why I'll have to think about it.

**Comment by yunjuc** [comment]
The relative attribute has two functions - to set custom position for itself and to allow the child elements to set custom position. (https://www.w3schools.com/css/css_positioning.asp).

I didn't see custom position setting in `.module`, and after I removed `position: relative`,  `Actions` and `Milestons` stay in the same position, so that removes the first concern.

For the second concern, I did a search on "className module" and found the compoents call this class are -`syllabus-upload`, `course-description`, `milestons`, `actions`, `enroll-card`, `my-articles`, `course-details` and `course-this-week`. 

Everything on the course Home works as usual. I can't find `syllabus-upload`,`enroll-card` and`my-articles`. If you can double check those compents and see if they have any popover or modal window, then I think we are good.

**Comment by yunjuc** [comment]
I tried a few things such as replacing `.milestone` with `.action` and the issue persists, so it's most likely `.module` caused the issue.

I still can't find the `syllabus-upload`, `enroll-card` and `my-articles` in the app, looking at the code they seem to be unaffected. 

I further removed some child elements code since `position: relative` isn't there anymore. If issue comes up, the alternative is to put the code inside the child.

**Comment by ragesoss** [comment]
EnrollCard appears if you put ?enroll at the end of the url.

MyArticles appears if you are enrolled as a student. (You can create a
CoursesUsers record with role 0 to test this.)

SyllabusUpload won't be in use at the same time as the stats modal.

**Comment by yunjuc** [comment]
@ragesosa I saw you just closed this. I meant to take another look for the failing checker. What was it about?

**Comment by ragesoss** [comment]
@yunjuc it was failing because a new version of rubocop was release, and the CI build was misconfigured to install and use the latest version of rubocop rather than the one from Gemfile.lock.

I fixed that with https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/e36acfbbbfe8fc2d1a643822541158f3fa92f1b3

I tried out your patch locally and couldn't find any style regressions, so I merged it. Thanks! :-)
