### ISSUE TITLE
Bug in lists displaying

### ISSUE THREAD

**Issue by urbanecm** [WikiEducationFoundation/WikiEduDashboard#1946]
Dashboard has some problem with displaying lists. I've added a dummy blank line after "list of hoaxes" in https://outreachdashboard.wmflabs.org/courses/Wikimedia_%C4%8CR/U%C4%8D_s_Wiki, some points of list fixed automatically on Wikipedia (https://cs.wikipedia.org/w/index.php?diff=16227423). After I removed the dummy blank line again, it broke again https://cs.wikipedia.org/w/index.php?diff=16227424. 

Dashboard seems to delete some endline characters before publishing on wiki.

**Comment by ragesoss** [comment]
This is because the Description field uses markdown, and then converts it to wikitext when it posts the on-wiki version using Pandoc. Pandoc renders some ambiguous markdown syntax to HTML (and from there to wikitext) differently from how the Dashboard renders it using the javascript library `markdown-it`.

In particular, Pandoc's default markdown spec expects a blank link before the start of a list:

```
# Not rendered as a list
Foo:
* bar
* baz

# Rendered as a list
Foo2:

* bar
* baz
```

I think I can fix this particular case by using Pandoc's option for GitHub-flavored markdown, which interpets both of those as lists.
