### ISSUE TITLE
Pagination element disappears if we go to another tab and then come back to Uploads

### ISSUE THREAD

**Issue by ihsavru** [WikiEducationFoundation/WikiEduDashboard#2028]

**Comment by ragesoss** [comment]
It looks like this is because the component remounts, with a reset of state, when you navigate away and back, but the pageCount is kept in state and only set via componentWillReceiveProps — which only fires when the props change after the initial render. So if the uploads are already received, there's no re-rendering from new props, and the pageCount never gets added to state.

I think the best solution here would be to move pageCount (at least) to a selector, so that pageCount is received as a prop. Potentially, currentPage could be moved to redux as well, so that all the current state could be replaced by props that come directly or indirectly from the global redux state. That way, the page would also be retained when switching between tabs.

Alternatively (and more simply), the pageCount could be also set within getInitialState.

Also, there's no need to keep `UPLOADS_PER_PAGE` in state. That can just be used as a constant wherever needed.

**Comment by aSquare14** [comment]
I'm working on this !
