### ISSUE TITLE
Provide a clearer notice when a program has no campaign

### ISSUE THREAD

**Issue by Samwalton9** [WikiEducationFoundation/WikiEduDashboard#2150]
A user had an issue (https://meta.wikimedia.org/wiki/Talk:Programs_%26_Events_Dashboard#Password_not_accessing_dashboard) with a program not having a campaign set. This meant the program couldn't be joined by other users.

When this happens the message users get is, I believe, "This course has not yet been approved for enrollment." It seems like we could display a more informative notice here, specifying the problem (no campaign) and noting more explicitly that users won't be able to join until it's set.

**Comment by ragesoss** [comment]
This is specifically for the case of the P&E Dashboard, rather than the Wiki Education Dashboard (which already has a different, detailed notification about the next steps for an unlisted course).

This is currently handled in the "Admin / Instructor notifications" of `course.jsx`. Tackling this issue would be a good opportunity to extract the logic for all the course-alerts to a separate component (and to further extract this particular set of messages related to the 'life cycle' of getting a new course ready for use into its own component).

**Comment by Samwalton9** [comment]
Done in https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/2174.
