### ISSUE TITLE
Add support for other Wiktionary namespaces

### ISSUE THREAD

**Issue by Samwalton9** [WikiEducationFoundation/WikiEduDashboard#2199]
Per https://meta.wikimedia.org/wiki/Talk:Programs_%26_Events_Dashboard#Wiktionary_content_namespaces - Namespaces 100 and 106 are useful but not currently tracked by default.

**Comment by hartman** [comment]
wgContentNamespaces

**Comment by Aeropio** [comment]
Hello I am current outreachy applicant and wants to work on this issue, please know the steps to reproduce this in my local

**Comment by ragesoss** [comment]
The way to replicate the problem would be to create a course with en.wiktionary as the home wiki, then go to en.wiktionary.org, find editors who have made recent edits in the Appendix (100) and Rhymes (106) namespaces, add them to your course with appropriate dates that include some of those edits, and then do a stats update for that course. The edits to those namespaces won't show up on the Dashboard, because the `replica` endpoint does not search those namespaces.

Fixing this well probably involves changes to both the Dashboard codebase and https://github.com/WikiEducationFoundation/WikiEduDashboardTools

**Comment by AmitJoki** [comment]
Fixing this should be easy now with the setup I've done in revisions.php Shall I go ahead and add 100 and 106 for wiktionary?

**Comment by ragesoss** [comment]
Yes

**Comment by ragesoss** [comment]
This is done.
