### ISSUE TITLE
Non-WikiEdu theme should be available

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#22]
It should be possible to configure the mainline codebase to use stylings that do not use WikiEdu's visual identity. So, make it possible via configuration to use Wikimedia colors (reds, greens, blues) and a generic logo, to change to the logo link (currently wikiedu.org) via config, etc.

**Comment by ragesoss** [comment]
Alternative logos are now possible. The one available so far is the Wikimedia logo. An alternative color palette would still be helpful.

**Comment by ntdb** [comment]
This should be relatively easy to accomplish because of our use of the Stylus preprocessor. The idea would be to have different versions of a single .styl file that define different color variables used throughout the application. Gulp would then generate a separate variation of main.css for each theme and rails would choose which to serve based on a `theme` key in `application.yml`.

**Comment by ragesoss** [comment]
This is far enough along to be functional for the alpha.
