### ISSUE TITLE
Code of Conduct for the Project.

### ISSUE THREAD

**Issue by aSquare14** [WikiEducationFoundation/WikiEduDashboard#2254]
https://github.com/WikiEducationFoundation/WikiEduDashboard/community
This link shows that we don't have a code of conduct. How about redirecting to https://www.contributor-covenant.org after adding a code of conduct section in the README.

**Comment by ragesoss** [comment]
We don't have a code of conduct specifically for this project, but per the end of the README, we follow the Wikimedia CoC: https://www.mediawiki.org/wiki/Code_of_Conduct

We could probably put a file just repeating the bit from the README so that it's easy to find programmatically (and so GitHub doesn't show it as missing).

**Comment by aSquare14** [comment]
True. I'll do that !

**Comment by aSquare14** [comment]
@ragesoss  Could you take a look at that link again ? It still says no code of conduct !

**Comment by ragesoss** [comment]
Yeah, that's weird. Maybe because it's so short? Oh well.

**Comment by aSquare14** [comment]
I think you have to propose from that link or something. Not sure though.
