### ISSUE TITLE
Removing a course participant doesn't cause template to be removed from wiki

### ISSUE THREAD

**Issue by urbanecm** [WikiEducationFoundation/WikiEduDashboard#2842]
If you remove a course participant, the participation template (for cs.wikipedia, it's Template:Nástěnka/Účastník) isn't removed from user page and user talk page.

**Comment by xiaobaioo7** [comment]
@ragesoss can I work on this one? Noted this issue is added to "Prague Hackathon" project, not sure if this issue is still relevant, please advise.

**Comment by ragesoss** [comment]
@xiaobaioo7 yes, go for it. It's something we identified as an issue during that Hackathon, but didn't get to it then.

**Comment by xiaobaioo7** [comment]
Hi, I started looking into this issue and have a few questions.

The issue mentioned the problem with user page. If I understand this correctly, these are the steps I followed to reproduce the problem:

1. I removed an editor A from a program B
2. I went to the user page for the removed editor A. But I don't see any indication of the program B on the user page. 

I am not sure if this issue still exists for the user page, or I could be missing something. Would you take a look or guide me through the repro steps?

Also, the issue mentioned the problem with user talk page, but I can't seem to locate the page. Can you help guide me through the repro steps?
p.s.: I found somewhere in the code that points to a user talk url like `https://${language}.${project}.org/wiki/User_talk:${username}`. Is this the user talk page?

**Comment by ragesoss** [comment]
Yes, you're on the right track.

These steps won't let you reproduce the problem locally, though, unless you your development environment configured to enable wiki edits.

For example, here's the user page for a student in one of the current course: https://en.wikipedia.org/wiki/User:Jfitz19

That template pointing to the course got added as one of the actions fired off by `EnrollInCourseWorker`, specifically, `WikiCourseEdits#enroll_in_course`.

The idea here would be to have a similar job for cleanup when a user leaves a course, which would search for and remove the course template from the userpage.

Yes, that's a user talk page at the end of your post. For example, https://en.wikipedia.org/wiki/User_talk:Jfitz19

**Comment by xiaobaioo7** [comment]
Thanks @ragesoss for the detailed explanation! 

You mentioned that this cannot be reproduced locally unless the development environment is configured to enable wiki edits. Can you shed some light on how to do that? Is that a configuration at the application level or at the wiki user level?

On an attempt to reproduce enrolling user in course to see the updated template in user page, in my test the program has a flag `:wiki_edits_enabled` set to true. Referring to sidekiq ui `http://localhost:3000/sidekiq`, the ui showed 2 processed entries shortly after the attempt. Does it mean the wiki edits are enabled and tasks to update user page and user talk page succeeded? I could be missing something, the 2 user pages don't seem to be updated with the templates.
`https://${language}.${project}.org/wiki/User_talk:${username}`
`https://${language}.${project}.org/wiki/User:${username}`

As a side note, before I installed redis server version 4, the steps above did not progress the tasks from `Engueued` state. It seems that this could relate to the sidekiq version installed in my environment. It turned out to be sidekiq version 6 with redis-server version 3. Reading from sidekiq's document, version 6 requires redis-server version 4+. The tasks only moved to `Processed` state after I installed redis-server version 4. Is it expected to use sidekiq version 6?

**Comment by ragesoss** [comment]
Yeah, you need redis-server 4 alongside sidekiq 6.

For enabling wiki edits, see https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/docs/oauth.md

You be able to test out almost all of it (and write specs for it) without needing to enable wiki edits, though. You can still check the output of what edits would have been made.

**Comment by xiaobaioo7** [comment]
Thanks @ragesoss for the clarification.

Referring to the `WikiCourseEdits#enroll_in_course`, it seems that when adding the template to user and user talk pages, what it does is to call the wiki api to prepend text to the given pages.

It looks like the call funnels to `WikiEdits#add_to_page_top` and call wiki api for the `edit` action. Does this look like one of the wiki api url?
`https://en.wikipedia.org/w/api.php?action=help&modules=edit`

From the url above, I see how we can make the request to add to the page top. However I don't seem to find out how to remove text from a page. I am assuming that we could use the same api to both add and remove the templates. Could there be a different way?

**Comment by ragesoss** [comment]
@xiaobaioo7 the way to remove text from a page is essentially to replace the current text with new text, so all the logic of finding and replacing the specific template will fall to our application.

We have some code that does this for slightly different circumstances in `WikiAssignmentOutput` (which is also used by `WikiCourseEdits`); it adds, replaces, or in a certain circumstance, removes, a template from an article talk page.

**Comment by gabina** [comment]
Just so you know, I'm working on this issue.
