### ISSUE TITLE
Create a JSON API for joining a course that does not require a passcode

### ISSUE THREAD

**Issue by ujjwalagrawal17** [WikiEducationFoundation/WikiEduDashboard#3034]
**Describe the feature you'd like**
- Create a JSON API for joining a course that does not require a passcode.

**Comment by ragesoss** [comment]
Does joining a course with a passcode work now? The endpoint for joining without one is exactly the same, you just don't need to include a passcode.

**Comment by ujjwalagrawal17** [comment]
No we don't have documentation for joining a course with passcode too.

**Comment by ragesoss** [comment]
Cool. Currently the way to join is to visit a URL like `localhost:3000/courses/test/New_Wiz_Wiz/enroll/<passcode>`

And without a passcode, just `localhost:3000/courses/test/New_Wiz_Wiz/enroll`

It will then redirect to the course page, with a flash message indicating the result.

I think to turn this into a JSON API, it would make sense to update the web behavior to also use a JSON post instead of the current redirect/reload flow. Wes and I will take a shot at doing that today, although it's a somewhat complicated refactor so we might not be able to finish it until next week.

**Comment by ujjwalagrawal17** [comment]
No issues I just figured out few tasks that I can do without the APIs like settings page to change between 2 servers (wiki education and outreach programs), about page of the app.

**Comment by ragesoss** [comment]
Hopefully you also have enough to go on for the other APIs, which do support JSON. If any of those need more documentation or otherwise don't work as expected, please ping.

**Comment by ujjwalagrawal17** [comment]
@ragesoss sure.

**Comment by ragesoss** [comment]
On the next deploy, the enroll endpoint will support JSON requests. It should work the same way as the HTML endpoint, which is just a GET request to `/courses/<course_slug>/enroll/<passcode>`.
