### ISSUE TITLE
Create a JSON API for organizer to create accounts for edit-a-thon participants. 

### ISSUE THREAD

**Issue by ujjwalagrawal17** [WikiEducationFoundation/WikiEduDashboard#3035]
**Description**
- Create a JSON API for organiser to create accounts for edit-a-thon participants.

**Comment by ragesoss** [comment]
I think this should work already. It's a PUT to `/requested_accounts`, with the following data:
`course_slug`
`create_account_now` — boolean, use `true` for a signed-in program organizer to create the account immediately, rather than add the request for later approval.
`email`
`passcode` — this should be available from the course data, if the user has access to it as organizer
`username`
