### ISSUE TITLE
Create a git pull hook to automatically update the packages and gems

### ISSUE THREAD

**Issue by AmitJoki** [WikiEducationFoundation/WikiEduDashboard#3480]
At WikiEduDashboard, there's a constant development and there's a constant changes being made to the versions of the packages or gems we use. Sometimes new packages/gems will be added.

When this happens, we have to manually do `bundle install` for gems and `yarn` for npm packages. Not doing this means we end up using the older packages/gems which might throw annoying errors.

This git pull hook will check for changes in the Gemfile or package.json and automatically runs the corresponding command.

You can have a look at https://gist.github.com/sindresorhus/7996717 to have a starting point.

This will not be a part of the setup and completely opt-in and will need some documentation to go with it.

**Comment by bwreid** [comment]
I feel a bit conflicted about this. While this seems like a nice, "quality of life" improvement, it could make this process more difficult to understand should something go wrong during it.

My thought would be to have a `.sample` githook file. In setup descriptions, this should be referred to as optional.

**Comment by AmitJoki** [comment]
Yes, this hook is not compulsory but only those who wish it can may be make a use of it. I thought of adding the documentation of it as a separate task, but I'll reword to include it now.

**Comment by urbanecm** [comment]
Hello @AmitJoki, could you please include information about which codebase this task is in the GCI copy, and inform students how should they submit the work? Should that be via GCI interface, github pull request or something else? I've also unchecked the Beginner task checkbox, and I recommend you raise the number of days available. I use that field to rate difficulty, and I personally think this task is one of the most difficult, since student would need to create a script from scratch rather than touch something already existing. Thanks!

**Comment by AmitJoki** [comment]
@urbanecm the task would be to modify the script I've already provided a link of, but yes, I think it could be increased. I've made it 5 days, is that okay? I've also added how it should be delivered.

**Comment by urbanecm** [comment]
Thanks, 5 days are okay IMO. You can also increase that limit for an individual student if they ask.
