### ISSUE TITLE
Admins should be able to search tickets by username and by message content

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#3588]
Admins can filter tickets by status and owner, but they can't search for them. As the number of tickets grows, and some don't go through email inboxes first, it would be nice to be able to search them.

### Related Files & Code:

This likely requires changes to the [TicketDispenser](https://github.com/WikiEducationFoundation/TicketDispenser) engine to add a search API, along with frontend changes in the Dashboard codebase to make use of it.

**Comment by ciphereck** [comment]
@ragesoss Can I start working on this?

**Comment by khyatisoneji** [comment]
@ciphereck are you working on this?

**Comment by ciphereck** [comment]
No. You can take it.

**Comment by epleaner** [comment]
@khyatisoneji any progress? Happy to hop in.

**Comment by ragesoss** [comment]
I don't think Khyati is working on this, @epleaner.

**Comment by epleaner** [comment]
For anyone wanting to get their dev environment up and running to work on this issue (setting up TicketDispenser and populating db with sample tickets), here are the steps I took:

1. Clone (or fork if you are making changes) [TicketDispenser](https://github.com/WikiEducationFoundation/TicketDispenser) as a sibling to your WikiEduDashboard directory (e.g workspace/TicketDispenser/ & workspace/WikiEduDashboard/)

2. In WikiEduDashboard repo:

   1. Modify Gemfile to using the local TicketDispenser gem instead of remote:

   ```ruby
   gem 'ticket_dispenser', path: '../TicketDispenser'
   # gem 'ticket_dispenser', git: 'https://github.com/WikiEducationFoundation/TicketDispenser.git'
   ```

   2. run ```bundle install``` 

   3. Make sure you have a user with super-admin permissions:

      ```ruby
      > rails c
      	 User.find_by(username: '<your username>').update_attribute(:permissions, 3)
      ```

   4. Modify dev.rake to also populate tickets:

      ```ruby
      ...
      require "#{Rails.root}/setup/populate_tickets"
      
      namespace :dev do
        desc 'Set up some example data'
        task populate: :environment do
          ...
          populate_tickets_demo
        end
      end
      ```

5. Run rake dev:populate
6. You should now see tickets in http://localhost:3000/tickets/dashboard



I recommend not commiting/pushing the above Gemfile and dev.rake changes, as they is specific to this issue.

**Comment by epleaner** [comment]
Hey, some questions about this issue:

1. How many tickets (ceiling estimate) should we expect to realistically be working with? It'd be helpful to know a good stess-test amount – currently testing with 200 open tickets. 

2. "search tickets by username" -> I'm assuming this means searching by ticket sender? Should we also support searching by ticket messages' senders?

Seems that as the Ticketing Dashboard is already fetching all of the ticket data to the client, it would be quicker to do the search client-side as well. This would save network requests, support offline searching, and matches the filtering functionality already present. I propose [redux-search](https://github.com/bvaughn/redux-search) to use, which fits in nicely with redux already being present, and supports web-workers out-of-the-box for scalability.

**Comment by ragesoss** [comment]
This is done now.
