### ISSUE TITLE
AssignButton popover goes off the screen when title is too long

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#3715]
For example:

![wikiedu_offscreen_assignment](https://user-images.githubusercontent.com/848483/73482531-c33aa080-4352-11ea-85fe-be1d483cf6f8.png)

Perhaps wrapping the title to multiple lines will fix it, or maybe some other CSS fix is the right solution.

**Comment by mattwarren10** [comment]
It looks like this issue is already resolved. Taking a look at these images, we find that the popover is accessed from a different button and in a different location.

Here is the old one:
<img width="1142" alt="Screen Shot 2020-02-01 at 9 01 40 PM" src="https://user-images.githubusercontent.com/13757305/74886626-a6d4c700-5346-11ea-9733-7956e0d63852.png">

Here is the new one:
<img width="1131" alt="Screen Shot 2020-02-19 at 6 34 25 PM" src="https://user-images.githubusercontent.com/13757305/74886642-b3591f80-5346-11ea-8ef6-bbd6355133a8.png">

Let me know if there was a pr that fixed this issue.

**Comment by ragesoss** [comment]
Yes, you're right. The issue became irrelevant because of the major layout change from https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/3579
