### ISSUE TITLE
Course clone tool prefilled data and validation needs improvement

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#386]
When a user clones a course, the default assumption should be that they are teaching the same course but in a different term, and we want the slug to be as meaningful as possible. Instead of adjust the course title by adding '(Copy)', the default should be to populate that field with the original title, and to leave the term field blank. For constructing the default slug (which gets changed when you save the course), it could be something like `/School/Course_(copy_from_Original_Term)`, but the term should be blank so that the user must input the new term.

The form does not currently give validation feedback (although it does prevent invalid duplicate slugs). Giving feedback for users trying to save the same  school/title/term as an existing course is especially important here, as users trying to clone a course for use in a second discussion section for the same term may try to save the exact same school/title/slug as the original.

The dates fields, weekdaypicker, and calendar should all be blank; the dates will almost certainly not be the same as the original, and we don't want users to accidentally save a new course without changing them.

**Comment by thenickcox** [comment]
In working on implementing a fix for this, I discovered we can't really `nil` out the start and end dates of the cloned course without a good deal of work because a lot of the server generated code depends on it. And on the front end, if we pass `null` or `''` start or end values into the date picker, which is 3rd party, it renders the string `invalid date`. So how would you like to handle forcing the user to change the dates? We could just put in today's date for both and disable saving until they change it…?

**Comment by ragesoss** [comment]
Can we catch `invalid date` and replace it with `''` after it comes out of the datepicker?

Using today's date is okay, if there's no way to just leave it blank on the frontend.

**Comment by thenickcox** [comment]
We have to set a value when we render the component, and the component handles that internally, so we have no control over it once the component takes over. So I'll just set them to today.
