### ISSUE TITLE
course_deletion_spec fails intermittently

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#3988]
`spec/features/course_deletion_spec.rb` is one of the browser specs that usually passes, but every once in a while fails on travis-ci, like this:

![Screenshot from 2020-04-21 23-11-16](https://user-images.githubusercontent.com/848483/79897355-7816b380-83be-11ea-8a88-d3c98a7a45e6.png)

Figure out why this test is flaky, and fix it.

**Comment by jproft** [comment]
@ragesoss It looks like a race condition. The test visits the course page, which appears to entail making 24 requests right off the bat. I read that `visit` does not wait, so while requests are still being made, the test goes on to press the "Delete course" button. It appears that many of the requests being made require methods labeled "course data JSON endpoints", which in turn requires the `set_course` method, which calls `find_course_by_slug`. So it seems like there are many opportunities for the course to be deleted before all of those `find_course_by_slug` calls finish.

I noticed that many of the other tests leverage `sleep`, and I imagine that using that here would solve this intermittent problem. However, I also read in several places that one should try to avoid using `sleep` since many Capybara methods will implicitly wait. Do you have any thoughts about this?

**Comment by ragesoss** [comment]
This makes perfect sense; it's definitely a race condition where the course gets deleted before the frontend JSON requests resolve.

This is one of the few cases where using `sleep` is the right move, I think. In general, it's easy to write bad Capybara tests where sleep is a workaround for a test that isn't taking advantage of Capybara's waiting behavior, for example by failing immediately when an expected element hasn't rendered yet even though it will render once all the typical JSON requests have completed. (I've made such mistakes many times, and fixed many of them; most of the remaining cases where we already use sleep probably also could be fixed with smart tweaks to the tests, but these ones are typically there still because the test intermixes expectations about what happens in the browser with expectations about the database, which is something I now try to avoid.)

In this case, Capybara can't help us with a record getting deleted while another request is already trying to look up that record.
