### ISSUE TITLE
The sandbox URL for an Assignment should be updateable

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4157]
### Current Behavior:
When a user gets an Assignment (ie, lists the article they will work on), the dashboard sets as sandbox url for that assignment. The normal behavior is that the sandbox is a userspace subpage that takes the name of the assigned topic. For example, if I (User:Ragesoss) get assigned the article "Selfie" on en.wikipedia.org, then the sandbox URL will be `https://en.wikipedia.org/wiki/User:Ragesoss/Selfie`

If a classmate gets assigned to the same article that another student is already assigned to, their assignment will have the same sandbox URL as the first one, so that they can work together in the same sandbox.

However, sometimes this isn't where the students want to draft their work. Common patterns include:
* a user starts their draft in another location before adding the Assignment on the dashboard
* a user manually begins working in their generic sandbox page, because it is linked from the top of the page on Wikipedia
* users assigned to the same article title are working independently and need separate sandboxes

### Desired Behavior:
The dashboard should have a way for a student or instructor (or admin) to update their sandbox URL to an arbitrary URL.

**Comment by rahahahat** [comment]
@rageross, I would like to work on this issue. However, i do have a few questions as i'm fairly new to rails.
1) For updating the sandbox url, do you specifically mean like an input, which allows the user to edit the `User:"new-url"` part of the url, for allotment of a separate sandbox?
2) Also, is this issue in the same context as #4276, If so should I look at the same files for a starting point. If not, could you please direct me towards a starting point.
Thanks alot.

**Comment by ragesoss** [comment]
1. Yes, something like that.
2. Yes, this is a closely related issue, although I don't thin they directly overlap. On the Rails side of things, the relevant places to look are the `Assignment` model `AssignmentsController`, and perhaps (for example code that interacts with Assignment records and the sandbox_url field) `AssignmentManager`.

**Comment by rahahahat** [comment]
@ragesoss Thanks, i'll get working.

**Comment by rahahahat** [comment]
@ragesoss Hello, sorry for a such a late update, I have been quite busy with university lately. However, these past couple of days I have made some progress on the bug. I have managed to get the frontend part done. Please see the attached video to see the URL update component. Just to elaborate a bit on it's implementation, I have defined a new component `EditSandboxUrl` (containing a `Popover`) wrapped with the `PopoverExpandable` HOC. I have also added an action in `assignment_actions.js` which makes calls to a new route `/assignments/:id/update_sandbox_url` in the API and updates the redux store (with the fetched updated assignment) through the `UPDATE_ASSIGNMENT` action. 
Regarding updating the sandbox_url, since we earlier talked about updating the `User:"new-url"` part of the url. A few edge cases that arise in my mind are:
1) What if a user of that username already exists?
2) What if a sandbox url already exists that is the same as newly updated one?

In these cases would updating the `User:` part of be the ideal choice or can we take another approach towards upating the url?
I'll open a pull request shortly so that you can see the code i've added. 
Thanks alot for the help and sorry again for holding this issue till now.

https://user-images.githubusercontent.com/62028695/107898310-52e9c780-6f33-11eb-8cfe-e985fab41fc5.mp4

**Comment by rahahahat** [comment]
@ragesoss Hello, I've open a pull request for the issue. Please review it.
Thanks.
