### ISSUE TITLE
SurveyResponseAlert emails should indicate which survey the alert is from

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4650]

**Comment by cyrillefr** [comment]
Hi @ragesoss , Can I work on this one ?

**Comment by ragesoss** [comment]
@cyrillefr sure. This is probably a pretty small issue.

**Comment by ragesoss** [comment]
Yes.

**Comment by cyrillefr** [comment]
Hello @ragesoss, I am facing difficulties completing this task.

I have looked at the DB to see how I could handle this issue. I have watched the associations between models, and may be I am missing something, but I cannot think of a way to get a relationship between an answer and a survey.

So I did a little test:
I went on /admin, then /surveys
- created 2 question groups (with 3 questions each)
- created 2 surveys
- assigned to each survey both question groups (no complains)

Then I went to http://localhost:3000/surveys/1/ to complete the survey #1:
every questions from both question groups = 6 answers to 6 questions

I have checked at http://localhost:3000/surveys/results
Each survey is 0% answered (which seems a bit strange btw)

I can download a CSV of survey #1.
BUT, I can also download survey #2, that is the same result as survey #1 (even though I did not attempt to take survey #2).

I think this is due to the models:
In the `surveys_question_groups` table(which is a join table), you can link a survey and question group. A question group may have surveys, and the other way around.

When you take(answer) a survey, you populate `rapidfire_answer_groups` and `rapidfire_answers` tables.

There is no direct link to a survey, but a link to question group. Which may have a collection of surveys. That means, there is no direct association between an answer and a survey, only between an answer and a question group. And a n-n relationship between question groups and surveys.

**Comment by ragesoss** [comment]
Oh... interesting. I didn't realize that an answer can't be traced back unambiguously to the survey it came from. The survey code is quite a mess, both in terms of database design and UI.

Still, in practice, we don't re-use question groups between surveys; we clone them and use the new question group for a new survey. So I think you could work around this problem by checking whether the question group is only part of only one survey, and if so, infer that it's the right one.

Alternatively, the email could just put the name of the question group, which would also provide the necessary context in most cases.
