### ISSUE TITLE
Silent javascript error when a course search returns no results

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4680]
### What is happening?

If you go to /explore and do a course search that returns no results, there is a JS error like this:

```
templater.js:37 Uncaught TypeError: Cannot read properties of undefined (reading 'childNodes')
    at n.getItemSource (templater.js:37)
    at new n (templater.js:6)
    at t.exports (templater.js:173)
    at Object.start (index.js:53)
    at new t.exports (index.js:261)
    at HTMLDocument.<anonymous> (course.js:21)
    at e (jquery.min.js:2)
    at t (jquery.min.js:2)
    at r (helpers.js:72)
```

It looks like this is because the jQuery code in `course.js` doesn't account for an empty table of results.

It has no visible effects, it just generates error logs that get sent to Sentry.

The fix should probably be done by adjusting the JavaScript (rather than tweaking the results HTML to meet the expectations of the JS).

**Comment by raffifu** [comment]
The problem happen because there are two section with `id='course'`
- 1st Section: show search result
- 2nd Section: show campaign course

It will throw an error when one of these element not contain class 'list' used in`list.js` dependencies. in this case, happen when return no results from search

The Best Practice is to change the `id` value from search section. Because as i know `id` params must unique (only one for one html page). then `course.js` must updated to recognize new `id` value

The second option (easy way) is to edit `_search.html.haml` and then delete `#course` if none result from search

I can work on this issue, but it will take a little time to setup the environment (because i'm new here)

**Comment by ragesoss** [comment]
@raffifu go for it. If you run into any problems setting up the environment, give me a ping. (If you like, you can also send me your email address and I can invite you to the project Slack.)

**Comment by raffifu** [comment]
Thank you for inviting me, this is my public email `ah2n85yos@relay.firefox.com` (If you can't invite me with these email, i will send my actual email). 

Anyway, i'm facing problem when setup dev env with docker. I can't open `/explore` because always redirect to `/`. I've copied `application.example.yml` and `database.example.yml`
![image](https://user-images.githubusercontent.com/22138274/143686562-2a082f3f-c16c-4d14-b718-82e1de5db50b.png)
This is the log from console [pastebin](https://pastebin.com/DRzLdyEN)

**Comment by ragesoss** [comment]
You need to create a default campaign, a Campaign record with a slug that
matches the default_campaign value from application.yml.

**Comment by ragesoss** [comment]
Running the `setup/populate_dashboard.rb` script would also work.
