### ISSUE TITLE
Improve input matching in WikiSelect component

### ISSUE THREAD

**Issue by zblace** [WikiEducationFoundation/WikiEduDashboard#4681]
### Current Behavior:
There is no way to set some of Wikipedia instances as main (home) ones.

### Desired Behavior:
Option to select HR, SH and BS Wikipedia if not ALL?

### Related Files & Code:
I have no code overview or skill toknow how this is managed.

### Additional context:
https://outreachdashboard.wmflabs.org/

**Comment by ragesoss** [comment]
You can set any of these as the home wiki. Each course/event can only have one home wiki; additional wikis should be added to the Tracked Wikis field.

For `hr` and `sh`, you may need to type out most of the domain before it shows up as an option in the dropdown, because other language codes that come earlier include those letters (ksh, chr). That can be confusing. An improvement would be to do the filtering based on matching the domain from the beginning, instead of matching anywhere the input is found, so that typing `sh.wiki` would not return matches for `ksh.wikipedia.org` and so on.
