### ISSUE TITLE
Training resources should have a search feature

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5007]
### Current Behavior:
There are lots of training modules about specific topics and specific task, but it's no always obvious where to find the training content about the topic you are looking for. Browsing the modules to find exactly what you are looking for is tedious.

### Desired Behavior:
There should be a search bar that can help you find training content related to arbitrary keywords or phrases, searching the content, titles, and descriptions of training slides, modules and libraries.

**Comment by marklocklear** [comment]
How do we set up /training in our local environment? When I got to http://localhost:3000/training I get a blank page.

**Comment by ragesoss** [comment]
In `wiki_education` mode, you can load the full set of training modules from .yml files by visiting `/reload_trainings?module=all`.

It would be a nice improvement to add a message or link on how to do this that would display when there are no training modules in the database.

**Comment by ragesoss** [comment]
I opened a separate issue for the latter: https://github.com/WikiEducationFoundation/WikiEduDashboard/issues/5094

**Comment by cyrillefr** [comment]
Hello @ragesoss , can I work on this one ?

**Comment by ragesoss** [comment]
Sure!

**Comment by cyrillefr** [comment]
Is there a pattern from an existing feature you want me to copy/get inspiration of ?
(/explore : there is an input box to look for courses, there is also a FAQ and I surely misses other ones).

Also, I have spotted a bug in `/reload_trainings?module=all` and possibly another one when modules are displayed.

**Comment by cyrillefr** [comment]
Hello @ragesoss,
regarding the courses search module, front-end is in React. The current code for listing training modules is in html/haml. I can mimick the back-end code of courses search, but for the front-end part, I guess it is better to stick with back-end html.

Regarding  the bug(?) I found out: on my local machine `/reload_trainings?module=all` causes a 500 error due to a `ActiveRecord::RecordNotUnique` at line `app/models/training_slide.rb:62`
It happens in the method `self.inflate` at the `slide.save` fragment. 

But the real problem is the first line `slide = TrainingSlide.find_or_initialize_by(id: all_content['id'])`
The population of the TrainingSlide object is made via the `training_content/wiki_ed` (slides and modules).
Id and slug are based on file names. 
Populating the db means ingesting those files and creating the matching records in DB with id & slug red.
But ...
As it appears there is on my dev DB some TrainingSlide objects with -another- id than the ones red from the files.
So, another object is created with another id aaand the same slug.
There is a unique index on the slug.
Therefore, one same slug for 2 objects -> fatal error.

I do not know why I have these kind of data on my local machine, I have made a few PR for this project, and I guess, at one time, I had to import data, which are now colliding with filenames that populate TrainingSlide object. But I cannot remember on which occasion.
So, there is a possibility to import data from files and from ... somewhere else, and get this bug.

My other issue is that I have empty slides for some Training modules, which is logical, since I cannot update :)
It also means that when I populated those data(training module + slides) the first time, I did not import a complete set.

**Comment by ragesoss** [comment]
>Regarding the bug(?) I found out: on my local machine /reload_trainings?module=all causes a 500 error due to a ActiveRecord::RecordNotUnique at line app/models/training_slide.rb:62
It happens in the method self.inflate at the slide.save fragment.

Ah, yes! This is a problem related to switching back and forth between `wiki_education` mode. If you load training content in one mode, and then switch, then loading training content again means you can run into collisions with duplicate slugs.

One reasonable solution would be to (in development mode only) delete all training data first, whenever `/reload_trainings?module=all` is called.
