### ISSUE TITLE
Course creation process needs more expectation-setting info

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#515]
The dashboard should make it more clear to users what the course creation process entails before launching it. In particular, it should mention that they should have their academic calendar on hand, because it's important to include all the school breaks and holidays before proceeding, in order to generate a timeline with appropriate dates.

**Comment by thenickcox** [comment]
@ragesoss is this copy you'll write?

**Comment by ragesoss** [comment]
@thenickcox Here's a first draft.

```
The course creation process will walk you through a series of assignment design decisions, and will produce a detailed timeline that you can use as a starting point. You can edit the timeline to fit your needs. Be sure to have your academic calendar on hand before you begin; the assignment design tool will use the meeting dates of your class — including any school breaks and holidays — to fit your timeline into the date range you choose.
```

**Comment by thenickcox** [comment]
cc @bmathews

**Comment by bmathews** [comment]
cc @rileywho

**Comment by rileywho** [comment]
Modal after clicking "Create Course"

<img width="638" alt="screen shot 2015-12-15 at 1 50 07 pm" src="https://cloud.githubusercontent.com/assets/2120466/11825248/cb6d9592-a332-11e5-8dd7-a84ed9df4cb4.png">

**Comment by ragesoss** [comment]
@rileywho Part of the context for this issue — in particular, the part explaining that the process will guide you through decisions — is that in user tests, some instructors felt like they were not ready to proceed with course creation after completing the training, because they didn't have all the details worked out. So I was imagining that at least that part of it would be something that they see *before* they click "Create Course" and help reassure them that they'll get help along the way.

**Comment by rileywho** [comment]
This issue is related to #544. I would recommend setting some time in the next year to look at optimizing the initial "Create Course" flow.

A couple thoughts. If the users don't feel prepared after the training it might be worthwhile trying out a solution in that area of the application. For example, having a "Next Steps" slide at the end of the *New Instructor Orientation*. The *My Dashboard* doesn't have the space to give the user complete context to the fine details of every action. 

Attached is an idea for a temporary solution. We can utilize the question mark icon that has been introduced on multiple pages. The user hovers over the icon/phrase, and they are presented with a warning that they should have their academic calendars at the ready. This solution could help the users who are really not sure if they should click the "Course Creation". 

The solution presented earlier would help give all users a heads up/reminder that they should have their academic calendars at the ready.

**Comment by rileywho** [comment]
This issue is related to #544. I would recommend setting some time in the next year to look at optimizing the initial "Create Course" flow.

A couple thoughts. If the users don't feel prepared after the training it might be worthwhile trying out a solution in that area of the application. For example, having a "Next Steps" slide at the end of the *New Instructor Orientation*. The *My Dashboard* doesn't have enough space to give the user complete context to the fine details of every action.

Attached is an idea for a temporary solution. We can utilize the question-mark icon system that has been utilized on a couple pages. When the user hovers over the icon/phrase, they are presented with a warning that they should have their academic calendars at the ready. This solution could help the users who are really not sure if they should click the "Create Course" button. Though there is a chance that the casual user will ignore this.

![screen shot 2015-12-17 at 2 43 14 pm](https://cloud.githubusercontent.com/assets/2120466/11884141/90e09a64-a4cc-11e5-9748-a1f816b3f3a9.png)

The solution presented earlier would help give all users a heads up/reminder that they should have their academic calendars at the ready.

<img width="638" alt="screen shot 2015-12-15 at 1 50 07 pm" src="https://cloud.githubusercontent.com/assets/2120466/11825248/cb6d9592-a332-11e5-8dd7-a84ed9df4cb4.png">

**Comment by ragesoss** [comment]
Since this is mainly relevant for first-time instructors, I was thinking that text could be added to the bit about "looks like you don't have any courses". When there are no courses, there's plenty of room!

**Comment by rileywho** [comment]
@ragesoss Thats an excellent point. Lets do that. The course creation process will walk you through a series of assignment design decisions, and will produce a detailed timeline that you can use as a starting point. You can edit the timeline to fit your needs. Be sure to have your academic calendar on hand before you begin; the assignment design tool will use the meeting dates of your class — including any school breaks and holidays — to fit your timeline into the date range you choose.

**Comment by rileywho** [comment]
![screen shot 2015-12-17 at 3 42 20 pm](https://cloud.githubusercontent.com/assets/2120466/11885247/cb48c0de-a4d4-11e5-8d1c-b4f796ec772d.png)

**Comment by ragesoss** [comment]
+1

**Comment by rileywho** [comment]
@bmathews Do you need the sketch file? Font size is 15px, color: #717171

**Comment by bmathews** [comment]
@rileywho nope, sounds good, thanks!

**Comment by ragesoss** [comment]
@bmathews while you're editing index.html, Here's updated empty-state text for the orientation block:

Before you create a course, let's go through orientation to help you get started. (It takes about 30 minutes to complete.)
