### ISSUE TITLE
Course weeks are created with duplicate `order` values

### ISSUE THREAD

**Issue by thenickcox** [WikiEducationFoundation/WikiEduDashboard#523]
This isn't helping at all with calculating the start dates for each week on the server.

```
[1] pry(#<#<Class:0x007fad05db4818>>)> course.weeks
[2015-12-09 16:44:35.192 DEBUG] Week Load (2.7ms)  SELECT `weeks`.* FROM `weeks` WHERE `weeks`.`course_id` = 10273
=> [#<Week:0x007facfaee2e98 id: 2130, title: nil, course_id: 10273, created_at: Thu, 10 Dec 2015 00:40:17 UTC +00:00, updated_at: Thu, 10 Dec 2015 00:40:17 UTC +00:00, order: 1>,
 #<Week:0x007facfaee2d08 id: 2131, title: nil, course_id: 10273, created_at: Thu, 10 Dec 2015 00:40:17 UTC +00:00, updated_at: Thu, 10 Dec 2015 00:40:17 UTC +00:00, order: 1>]
```

**Comment by thenickcox** [comment]
This has apparently been happening since 11/18, according to my db.

**Comment by thenickcox** [comment]
@ragesoss Is it just me, or did we know this? I feel like we've talked about this.

**Comment by ragesoss** [comment]
@thenickcox yeah, you pointed this out to me recently, and you said it happens when you add a new assignment to a course that already has weeks. (I never tested whether it also happens if you delete all the weeks, and then open the wizard again.)

Per that discussion, it's fine to disable the 'add assignment' tool for courses that already have some weeks.

**Comment by thenickcox** [comment]
No, I mean this happens on the initial creation. Course updates the week order on `before_save`, but this doesn't happen when you first create a timeline.

**Comment by ragesoss** [comment]
@thenickcox ah! Well, then I've no idea. I guess just a bug in the handling of the wizard data?

**Comment by thenickcox** [comment]
Looking into it now.
