### ISSUE TITLE
Error when editing cloned conditional questions in certain situations

### ISSUE THREAD

**Issue by Aminehassou** [WikiEducationFoundation/WikiEduDashboard#5315]
### What is happening?
When attempting to edit a cloned question that is also a conditional, an error is returned if the original question that the conditional is based on has been deleted.

### To Reproduce

Make sure you're logged in and have administrator permissions
1. Go to `/surveys`
2. Click on the "Question Groups" tab
3. Click "New Question Group"
4. Create the question group (group details are irrelevant)
5. Edit the question group, create two questions, one question (q1-cond) should be a conditional based on the other question (q1)
6. Clone the conditional question (clone q1-cond)
7. Delete the initial question (delete q1)
8. Try editing the conditional question or its clone (edit q1-cond or clone of q1-cond)

### Expected behavior
The edit page loads and the user can edit the question as they please

### Videos
[Screencast from 03-19-2023 01:21:01 AM.webm](https://user-images.githubusercontent.com/39999898/226147036-94191ac5-a768-4acc-b2d2-a1472e0ed7a1.webm)

### System Information

 - OS: Ubuntu 22.04.1 LTS
 - Browser: Google Chrome 110.0.5481.77 (Official Build) (64-bit)

**Comment by ragesoss** [comment]
Very nice bug report @Aminehassou !

**Comment by leevic31** [comment]
I would like to work on this

**Comment by Abishekcs** [comment]
@ragesoss  i can work on this

**Comment by Abishekcs** [comment]
Update on this bug -
1) The bug occurs when editing a conditional question, `whether it is a clone or not`.
2) If the original question, on which the conditional logic is based, is deleted.
3) The bug triggers an error when attempting to edit the conditional question, but only if there are two questions remaining in the question group after the deletion.

[Edit Error.webm](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/74126284/62c02a3b-2347-430a-bdfa-5fa443da77dc)

**Comment by Abishekcs** [comment]
<b>Cause of the error -</b>

1) When a "Conditional Question" is created, the model object or record of the "Conditional Question" includes an attribute called `conditionals`, which stores the `question ID` of the original question it is based upon. 

![Screenshot from 2023-06-18 22-19-04](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/74126284/b3796ef4-a838-41c7-b10d-6367efee5075)


2) However, when the "Original Question" is deleted, the "Conditional question" still retains the `question ID` of the "Original Question", which no longer exists. This mismatch between the stored `question ID` and the actual existence of the question leads to an error.

3) To trigger the error, the `Edit` action needs to be performed on the conditional question after the deletion of the original question. Additionally, there must be at least `two questions` remaining in the "Question Group" after the deletion for the error to occur.

4) When the condition `if @question_group.questions.length > 1` in the `_form.html.haml` file evaluates to true, the `.survey__question__conditional-row{"data-conditional" => question_conditional_string(@question)}` method is called in the backend. This method receives the model object or record of the current conditional question as the `@question` parameter.

5) Within the` question_conditional_string` method in the `surveys_helper` file, the logic currently handles two scenarios:
  a) It returns an `empty string` if new question is being added (no existing conditionals).
  b) It returns the question ID stored in `question.conditionals` for the original question on which the conditional question is based.

6) However, there is no code in place to check whether the original question still exists or handle that scenario before returning its `question ID` `question.conditionals`.

7) Which  leads to the  `id` in `handleConditionalSelect(e)` in the `SurveyAdmin.js` being an empty string and the assignment `this.conditional = {};` will not occur, and the this.conditional object will not be created.

8) Which ultimately leads to `this.conditional.answer_value = target.value;` in `handleConditionalAnswerSelect` giving an error since `this.conditional = {}` is not initialized, giving the error - `TypeError` Cannot set properties of undefined (setting `'answer_value'`).

**Comment by Abishekcs** [comment]
**Cause of the error -** 

1) When a "Conditional Question" is created, the model object or record of the "Conditional Question" includes an `attribute` called `conditionals`, which stores the `question ID` of the "Original Question" it is based upon.

![Screenshot from 2023-06-18 22-19-04](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/74126284/85c99366-d296-4a22-9041-3a8cf6f24c73)


2) However, when the "Original Question" is deleted, the "Conditional Question" still retains the `question ID` of the "Qriginal Question", which no longer exists. This mismatch between the stored `question ID` and the actual existence of the `question` leads to an error.

3) To trigger the error, the `Edit` action needs to be performed on the "Conditional Question" after the deletion of the "Original Question". Additionally, there must be at least `two` questions remaining in the `question group` after the deletion for the error to occur.

4) After Clicking the `Edit` if the condition `-if @question_group.questions.length > 1` in the `_form.html.haml` file evaluates to true, the `.survey__question__conditional-row{"data-conditional" => question_conditional_string(@question)}` method is called in the backend. This method receives the model object or record of the current conditional question as the `@question` parameter.

5) Within the `question_conditional_string(question)` method in the `surveys_helper` file, the logic currently handles two scenarios:
  a) It returns an `empty string` if new question is being added (no existing conditionals).
  b) It returns the `question ID` or `nil`(if the question is not conditional) stored in `question.conditionals` for the original question on which the conditional question is based.

6) However, there is no code in place to check whether the "Original Question" still exists or handle that scenario before returning its `question ID (question.conditionals)`.This leads to the `bug`.

7) Which  leads to the  `id` in `handleConditionalSelect(e)` in the `SurveyAdmin.js` being an empty string and the assignment `this.conditional = {};` will not occur, and the `this.conditional object` will not be created. 

8) Which ultimately leads to `this.conditional.answer_value = target.value;` in `handleConditionalAnswerSelect` giving an error since `this.conditional = {}` is not initialized, giving the error - `TypeError` Cannot set properties of undefined (setting `'answer_value'`)

**Comment by ragesoss** [comment]
Great research, thanks @Abishekcs !

**Comment by ragesoss** [comment]
i agree, that doesn't make sense. anything you can do to make the behavior of conditional questions more consistent and sensible would be good, as long as it won't break existing surveys that use conditional questions that don't currently trigger errors.

**Comment by Abishekcs** [comment]
Okay
