### ISSUE TITLE
enroll link takes user directly to Wikipedia

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#534]
An enroll link still takes a student directly to the Wikipedia login. For example, https://dashboard-testing.wikiedu.org/courses/Wake_Forest_University/Race,_Class_Gender_and_Sexuality_(Spring_2016)/enroll/nycwsupi

I thought we implemented an onboarding / confirmation module on the course pages, so that students would get context before being thrown over to Wikipedia, and would be able to confirm / cancel before being added. Did that get lost somewhere and not make it to staging, or has it not been implemented yet?

cc @bmathews

**Comment by bmathews** [comment]
That URL (`/enroll/{code}`) is still used for the _actual_ enrollment api call, but a different url (`?enroll={code}`) is now what's generated to send to students. The query param based url is what shows the onboarding/confirmation experience. 

![image](https://cloud.githubusercontent.com/assets/848347/11825919/e6c6d084-a336-11e5-9393-00984fb4efa4.png)

It's true though that any of the existing links sent out to users won't give them that onboarding/confirmation experience when joining the course. Since it would be difficult to render the course for that `/enroll/{code}` route, we could instead force a redirect to `?enroll={code}` and set up a different endpoint for the actual enrollment api call.

Let me know if any of that doesn't make sense!

**Comment by ragesoss** [comment]
Here's the corresponding spec: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/spec/features/student_role_spec.rb#L133

It is marked pending because of random failures on Travis, but it's actually broken now because it doesn't handle the new onboarding process.

**Comment by ragesoss** [comment]
Oh, great! @bmathews we need to update the link that shows up when (as instructor or admin) you click "enrollment", because that is still the enrollment api call and not the new enroll param version.

**Comment by bmathews** [comment]
@ragesoss Ah, I had never discovered that functionality before! I'll fix that and take a look at those tests. Thanks for catching that!

**Comment by bmathews** [comment]
Fixed
