### ISSUE TITLE
Training Library pages with incomplete translation pages show raw HTML

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5383]
### What is happening?

When the Dashboard language is set to Spanish, this page shows a lot of raw HTML tags that shouldn't be there:

https://outreachdashboard.wmflabs.org/training/editing-wikipedia

![spanish html](https://user-images.githubusercontent.com/848483/235257431-9a4f2ce4-7274-484f-b95d-82aa229594d2.png)

This is probably related to the fact that the source page for the library description is enabled for translation on meta, but is not translated: https://meta.wikimedia.org/wiki/Training_modules/dashboard/libraries/editing-wikipedia/es

However, even in such a situation, the Dashboard should be falling back to English without introducing these unexpected raw HTML tags.

**Comment by Bharadwajshivam28** [comment]
@ragesoss Can i work on this issue

**Comment by Bharadwajshivam28** [comment]
@ragesoss Hi I want to work on this issue but can you provide some resource which can help me as I am new in this community and it is going to be my first Issue in this project

**Comment by Bharadwajshivam28** [comment]
@ragesoss can you please help me like under which folder/file i can find the source code of this language switching .. as i  am new beginner but i know how to fix it but i am facing issue in finding under which file/folder the source code this can be found

**Comment by ragesoss** [comment]
I don't think this is a good issue for you, as it involves a fairly complex set of interacting systems and code. I recommend working on the admin link highlighting bug that you were exploring.

**Comment by Bharadwajshivam28** [comment]
okay sir

**Comment by cyrillefr** [comment]
Hello @ragesoss,

The unwanted span tags seen on screen come from the DB (`library = TrainingLibrary.find_by(slug: "editing-wikipedia")`).
DB that is populated by `/reload_trainings`.
Which means that: `library[:translations]["es"] `exists and is displayed (with the extra html tags that are escaped).
But, for this page, for example, `library[:translations]["fr"]` is nil and english(default) is displayed.
Page in Spanish cannot be defaulted in this case because it simply exists in DB:
`library[:translations]["es"][:introduction]`
`=> "<span lang=\"en\" dir=\"ltr\" class=\"mw-content-ltr\">This set of modules\nhelps new editors get etc .`


This html comes from the page export:
https://meta.wikimedia.org/w/index.php?title=Special:ExportTranslations&language=es&group=page-Training+modules%2Fdashboard%2Flibraries%2Fediting-wikipedia
It also true for the Ukrainian translation:
https://meta.wikimedia.org/w/index.php?title=Special:ExportTranslations&language=uk&group=page-Training+modules%2Fdashboard%2Flibraries%2Fediting-wikipedia

But NOT for the swedish translation:
https://meta.wikimedia.org/w/index.php?title=Special:ExportTranslations&language=sv&group=page-Training+modules%2Fdashboard%2Flibraries%2Fediting-wikipedia

Why is that ?
The Spanish and Ukrainian translations are not finished (state in progress - you need to scroll a bit)
https://meta.wikimedia.org/w/index.php?title=Special:MessageGroupStats&language=uk&group=page-Training+modules%2Fdashboard%2Flibraries%2Fediting-wikipedia

My guess is for each missing translation, there is an extra span that is generated.

There is nothing to do at the client side (display).
I would say to avoid this issue is that the application should download only translations that have the completed state.
And modify the code that imports the data to look at some state parameter if that exists and not to populate the DB with translations in progress.

**Comment by ragesoss** [comment]
Thanks, great research!

Maybe the right strategy here is to scan for and remove those spans during the parsing process. That way, we could still support content that is partially translated.

**Comment by cyrillefr** [comment]
That was also my first thought.

Then I thought: it will take longer to import/update and there may be some other tags that can be generated.

And also, why a semi translated document ? If someone can read a partially translated document, this someone can read the whole document in English. Also, how can the reader be sure to understand the non translated part. 

As a non native English speaker myself, I go either for full English of fully translated.

Though removing the extra html will tidy the page.

**Comment by ragesoss** [comment]
You make good points... most people for whom a partial translation is fine would also be able to read the full English version. However, the way the MediaWiki translation system works is that a wiki page with translation tags gets parsed into separate translation messages, so you can update existing content in just a few places (or add some new content), and then translators will only need to update or add the ones that changed. So if we drop incomplete translations, that means all translations will be disabled any time there's even a small change to the source version. There can be a long lag between making a change to a source page and the corresponding translations getting updated.

I think that this bug with the partial translations is also only present on the Library page (and maybe on Module index pages as well), as the content of individual slides get handled as HTML anyway, so partial translations already work there.

**Comment by cyrillefr** [comment]
Aaaahh. I was not aware of how the translation mechanism was at work.
I better understand the necessity to stick with partial translations then.

Since I have begun to dig a bit, may I work on this issue ?

**Comment by ragesoss** [comment]
Yes!  :-)
