### ISSUE TITLE
Campaign 'programs' tab should be sortable by start date

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#5572]
### Current Behavior:

The Programs/Courses tab of a campaign, such as https://dashboard.wikiedu.org/campaigns/pcori_student_program/programs , may include courses that took place at different times. There's no way to sort them to see the most recent ones first.

### Desired Behavior:

There should be a 'start date' column, and the list should be sortable by that column. If it's easy to do so, this probably make sense to add to other course lists that use the same templates as well.

**Comment by SainiAditya1** [comment]
@ragesoss  ,I want to work on this , Please assign this to me

**Comment by ragesoss** [comment]
@SainiAditya1 we do not assign issues, but you are welcome to work on it!

**Comment by darshil89** [comment]
@ragesoss , we can also add newest and oldest option in the filter (which can fetch the Programs/Courses according to time) . But what do you mean exactly by the start date column ? 
is it a date from where all the programs will be list in order or just a program have that date ?
I would like to suggest there should be a select date instead of start date where user can get the Programs/Courses of that particular date , moreover we can also have 2 filter of newest and oldest as i mentioned above .

Should I proceed with this approach ?

**Comment by ragesoss** [comment]
@darshil89 each Course record has a `start` and an `end` datetime attribute, which represents the span of time where the course is happening. The Dashboard is keeping track of edits that happen during that span for each course.

We normally use a Campaign to keep track of the set of courses that are happening at basically the same time, like Fall 2023 or Summer 24 (corresponding to academic semesters). However, we also use Campaigns to represent sets of courses that have other things in common, like the courses that participated in an initiative to create biographies of under-represented people in STEM fields, and these often span a longer period of time. So the use case here is to be able to sort the list of courses in such a campaign so that we can easily see which courses happened when. The `start` date is most useful way to do that.

So the idea for this ticket would be to add a `start date` column to the table of courses, and allow it to be sorted by that value.

**Comment by Joice-crypto** [comment]
Hello could I work with this?

**Comment by om-chauhan1** [comment]
@ragesoss  Please correct me if i am wrong, after reading the conversation above i found that there should be column of start date (property of every course/program) near this given column of creation date and we are able to select this option of start date in the drop down menu in order to sort all the programs accordingly.
Image for reference : 
![image](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/119471995/03427af1-fc07-4926-b55e-34390c221e11)

This comment is just for validation whether i or anyone is working in the right direction.

**Comment by ragesoss** [comment]
@Joice-crypto sure, go for it.
