### ISSUE TITLE
Language Translation is not translating all textual content including the footer line.

### ISSUE THREAD

**Issue by om-chauhan1** [WikiEducationFoundation/WikiEduDashboard#5584]
### What is happening?
The bug is that whenever we want to change the language of website then some textual content remain untranslated to the desired language.

### To Reproduce
> 1. Go to home page or any give route.
> 2. Click on the arrow of drop down menu (top left in the navigation bar of header).
> 3. Scroll down and select the language of your choice.
> 4. The footer line and some part of text on every page remain untranslated.

### Expected behavior
The translation service should translate every textual content available on the web page to the desired language.

### Screenshots for reference

1. The footer line on every page remains untranslated :
![image](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/119471995/801333f9-9b3c-4a9d-8495-43602436ed4c)

2. Route = "http://localhost:3000/?locale=ja" :
![image](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/119471995/d43c7bcb-be5c-437f-b4a3-329e87143987)

3. Route = "http://localhost:3000/courses/ABC_Institution/Testing_program/uploads" :
![image](https://github.com/WikiEducationFoundation/WikiEduDashboard/assets/119471995/8b55b022-8102-4ce2-a146-40be5920ca0e)

### System Information

 - OS: [Fedora Linux]
 - Browser [e.g. brave]
 - Version [39]

**Comment by ragesoss** [comment]
Thanks!

The translations are done on by volunteers on translatewiki.net. If there are specific strings that are hard-coded in English and are not available for translators to work on, those are bugs that can be reported (either individually or in batches). But the expected behavior for when a string has simply not been translated yet for a particular language, the intended behavior is to fall back to English. We don't expect 100% translation of all languages, and missing translations are not considered bugs.
