### ISSUE TITLE
Common javascript error prevents overview from loading Description and ThisWeek

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#623]
See https://sentry.wikiedu.org/wikiedu/production/issues/117/

This seems to be happening a lot lately, and I was able to replicate it occasionally on Iceweasel; when it happens, the overview gets stuck on the loading animation.

Maybe it's a race condition for the different API calls that fire off when you load a course page?

**Comment by ragesoss** [comment]
I think maybe I broke things with 228b88ba19727e328d36b51b3c9e05ffcbc5d8a7

Could you take a look, @thenickcox? I maybe got ahead of myself with boldly meddling with React stuff.

**Comment by thenickcox** [comment]
@ragesoss @bmathews and I were looking at data syncing issues, and that's why I specifically used `week.blocks` instead of getting them out of the `BlockStore`. Problem is, we weren't confident enough to get rid of the process of getting them out of the `BlockStore` altogether, so we kept it in some places.

One solution I see here is just `_.sortBy week.blocks, (blk) -> blk.order`. And I wouldn't feel bad about that _in the least_. 

@bmathews Can I get a second opnion?

**Comment by ragesoss** [comment]
@thenickcox sounds good to me.

**Comment by bmathews** [comment]
Sounds fine to me, or sort it on the server?

**Comment by thenickcox** [comment]
@ragesoss Might make more sense to sort on the server, unless you can think of a reason we'd ever just want the `blocks` object not sorted by order.

**Comment by ragesoss** [comment]
@thenickcox as a general rule, I'm happy whenever we can move more things to the server. Feel free to make that switch. I'll open an issue for it.
