### ISSUE TITLE
Dependency on remote template is fragile

### ISSUE THREAD

**Issue by adamwight** [WikiEducationFoundation/WikiEduDashboard#647]
I'm not sure I understand what's going on here, but when I enrolled my sock in a course, the following wikitext was mirrored onto the sock's user page:
> {{localhost:3000 sandbox}}
That doesn't work at all, obviously...

Shouldn't we do the template substitution from Ruby, instead?

**Comment by ragesoss** [comment]
Maybe. There are some big advantages to using templates, though, for things like this. It doesn't leave a huge mess of html-ish markup, and it can be edited later. For Wiki Ed's purposes, that makes it worth it. For i18n, though, maybe some fallbacks for when the appropriate template doesn't exist on the target wiki?

**Comment by adamwight** [comment]
Good point, onwiki templates could be a win, but languages are hard.  I think [Content Translation](https://www.mediawiki.org/wiki/Content_translation) faces a similar problem, because there's no map for aliasing templates across languages or projects, and no common lexicon.

**Comment by ragesoss** [comment]
I've thought about this off and on, and I think the only good way to handle this will be to roll out on-wiki posting on a wiki-by-wiki basis, since the types of edits that we want to automate are likely to vary from wiki to wiki and we'll want to have some participation from users on that wiki. Closing this on the assumption that we probably won't move away from relying on remote templates, even if/when other languages start to get enabled for on-wiki posting.
