### ISSUE TITLE
Popup is not eager to popdown

### ISSUE THREAD

**Issue by adamwight** [WikiEducationFoundation/WikiEduDashboard#648]
![no_popdown](https://cloud.githubusercontent.com/assets/819437/12835738/96bea61c-cb67-11e5-9cdb-07e98652fa0a.png)

Clicking outside the box should cause it to disappear.
The <escape> key should also do so.

Neither does, I have to click outside the popup but within the course row to make the popup go away.

**Comment by ragesoss** [comment]
I think the way to solve this would be with the `ClickOnOutside` high order component, which is doing exactly what we want in the DatePicker component. But my attempts to make it play nicely with the way these popover buttons are implemented — using UIActions and UIStore rather than component state — have all failed so far.
