### ISSUE TITLE
Trained students popover not available on mobile

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#67]
On staging, the login button is beneath the logo on mobile, rather than top left.

Also, the popovers are no longer working on mobile.

**Comment by ntdb** [comment]
I intentionally moved the login button below the logo on mobile to make the use of space consistent across login states. There's not enough room for the link on the top right in mobile.

Popovers have never worked on mobile due to the lack of hover state. What would an ideal replacement be?

**Comment by ntdb** [comment]
Login button location is fixed in course_pages branch.

Will discuss possible solutions for displaying trained student counts on mobile with Ivan. Tap-to-display is functional but there's nothing in the designs to indicate that functionality.

**Comment by ntdb** [comment]
<img width="311" alt="screen shot 2015-07-28 at 11 13 05 am" src="https://cloud.githubusercontent.com/assets/2095463/8939741/1e6f537e-351b-11e5-8c5b-6a8fd5f6f1e1.png">

Desired improvements for the css-driven "popovers":
* Change CSS classes to use the term "tooltips" to avoid confusion with React-driven popovers
* Adjust implementation for improved sizing/locating
  * Smart width/height based on window and content size
  * Left/right/top/bottom based on available space in window
* Ensure mobile functionality (tap-to-open)
* Add indicators to triggers (no hover state on mobile). Maybe a dotted underline or an `:after` icon

Using a library for this is totally fine, [Tether](http://github.hubspot.com/tether/) might be a good place to start. It would also be cool to use React for this but we would need to "Reactify" the index page in order to use the tooltips there as well.

**Comment by ragesoss** [comment]
Cannot replicate anymore. Likely this was a browser implementation that now handles this automatically.
