### ISSUE TITLE
Conditional questions do not behave correctly

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#738]
I've got a conditional question for if the user selects 'no' for 'do you plan to teach with Wikipedia again': https://dashboard-testing.wikiedu.org/rapidfire/question_groups/5/answer_groups/new

It showed up once for me — and did not disappear when I went back and changed the condition answer — but now it will not show up at all.

**Comment by ragesoss** [comment]
I'm not sure if this got fixed by a subsequent build or if it was just some broken state that I got into, but that example is now working properly, both for the initial selection and if I go back and change the condition answer.

**Comment by hudakdidit** [comment]
@ragesoss yeah the conditionals regressed late yesterday due to a few changes. I've been working to resolve them today. The multi-select **checkbox** and **select ** conditionals still need some more work. I'll open a ticket specifically for those question types, and maybe we can track types individually in separate git issues for this feature?
