### ISSUE TITLE
Hot loading/No hot loading build process lacks documentation

### ISSUE THREAD

**Issue by thenickcox** [WikiEducationFoundation/WikiEduDashboard#839]
Coming back to this project after a while, it was frustrating for JavaScript not to work as expected when running `gulp`, and to have to dig around to find out why. I still lack the necessary understanding of the history behind why there are two options (and what exactly they do and why), so I wouldn't be a good candidate to write this, but I'd love for the next person to come along not to have to hunt down how to make JavaScript Work as Expected :tm:.

**Comment by ragesoss** [comment]
The way it is expected work is that `gulp` will Just Work™, while if you want hot-loading, you should use `gulp hot-dev` and also set `hot_loading: 'true' in your `application.yml`.

The reason is that hot loading means that the javascripts load from a different port, and that breaks things for developers who are using a vagrant environment. So we wanted the default way of just running `gulp` to work by default, and make `gulp hot-dev` an advanced option.

**Comment by thenickcox** [comment]
Oh, if only that were the case. I ran `gulp` and made several changes, and it seemed as though `watch` had no effect, which is what got me to start down this rabbit hole.

**Comment by thenickcox** [comment]
I'm trying to document when this happens, but I had to restart my machine this morning, and `gulp` stopped picking up my changes.

**Comment by thenickcox** [comment]
Turns out on-demand JS compilation broke when we added hot reloading, so we'll add this to the technical debt to address later in the month.
