### ISSUE TITLE
Article titles do not appear for many Assigned Articles after Articles Edited have loaded

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#869]
This page has more than 500 edited articles: https://dashboard-testing.wikiedu.org/courses/test/Multiwiki_Stats_Test_%28test%29/articles

While the articles are still loading, the assigned articles works fine:

![loading screenshot](https://cloud.githubusercontent.com/assets/848483/15366714/77b4ef00-1cda-11e6-963d-315c8a058380.png)

After the articles have loaded, the assigned articles render incorrectly:

![after articles load](https://cloud.githubusercontent.com/assets/848483/15366733/8a2569d0-1cda-11e6-9e9b-c52a3faecf66.png)

Maybe this is from React components getting pushed out of memory?

**Comment by ragesoss** [comment]
This is also happening at the scale of a real course, with 60+ articles edited: https://dashboard.wikiedu.org/courses/Emerson_College/World_Drama_%28Spring%29/articles

**Comment by mattfordham** [comment]
With regards to some assignments missing a "title", it is because not all articles in that table have a "formatted_title" value. I'm not 100% sure why yet, but I believe it has to do with this line: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/1c13cc65c35f5cc6f0de9d4cd6c7b190512a969e/app/assets/javascripts/components/assignments/assignment.cjsx#L11

Only some articles are going through the `articleFromAssignment` util.

**Comment by ragesoss** [comment]
Fixed with the merge of 'Available Articles'
