### ISSUE TITLE
If mulitple questions are conditional on the same one, only the last is shown

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#934]

**Comment by mattfordham** [comment]
I believe this is the problem area: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/app/assets/javascripts/surveys/modules/Survey.js#L535

Only one `$question` is allowed to be associated with a specific value (`this.surveyConditionals[question_id][value]`). The last one always replaces the earlier. 

A solution for this would be to collect an array of questions, as opposed to just one. That will require a little refactoring. Probably a 3-4 hour thing. 

Let me know if you like me to work that in to my schedule.

**Comment by ragesoss** [comment]
Yes please. The refactoring itself will probably also be beneficial.

**Comment by mattfordham** [comment]
Cool. I might be able to fit in tomorrow, but if not, it might be first half of next week. That ok?

**Comment by ragesoss** [comment]
Yep. No rush. We won't be deploying any new surveys any time soon.

**Comment by mattfordham** [comment]
I think I've got a fix for this here: https://github.com/WikiEducationFoundation/WikiEduDashboard/commit/6d2b1f82ad77d982c0fdafd3ed430b464bba3dfb

While it too a while to get there, the solution is pretty simple. Thanks to jQuery elements being arrays, most of the existing code "just worked" with a collection of related questions even though the original intent was for there to be only one. The change was to add to a collection within the loop, instead of replacing it each time.

**Comment by mattfordham** [comment]
@ragesoss I just pushed another commit on this. Hopefully the bug related to some conditional questions not showing up is resolved. Also, I opted to handle the "Next" vs "Submit" thing mostly on the client side. The view just renders "Next" and we swap out "Submit" when things run in JS.
