### ISSUE TITLE
Cannot drag block into empty week

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#958]
If you try to drag and drop a timeline block into an empty week (in Arrange Timeline mode), you cannot drop it into that empty week. The only way to get it to move is using the block up/down arrows.

**Comment by mattfordham** [comment]
The problem here is that the blocks are both the `DragSource` and the `DropTarget`s, and are composed via HOCs in a nested fashion. 

![image](https://cloud.githubusercontent.com/assets/292703/18969143/bd5985b4-8640-11e6-8e1b-389e2aeefdfa.png)

When a week has no blocks there are no `DropTargets` within it. 

Two ideas for addressing this:
- Ensure weeks always have a block within them by creating temporary "No blocks in this week" blocks that can act as targets.
- Make the weeks themselves targets, but only when empty.  

I am guessing the former above will be much easier, but either way will likely be 0.5-1.5 day job.

**Comment by arreche** [comment]
I am Learning a little bit about that [React DnD](https://react-dnd.github.io/react-dnd/docs-overview.html) before to start.

**Comment by patmbolger** [comment]
Note: there was some work performed on this story (still incomplete).  That can be seen in this "work in progress" PR: https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1210
